language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - master

services:
  - memcached
  - redis-server
  - mongodb

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - make depend
  - make configure

script:
  - make lint
  - $HOME/gopath/bin/goveralls -service=travis-ci
